version: "3.9"
services:

  filestorage-service:
    build:
      context: .
      network: host
      dockerfile: filestorage-service/Dockerfile

  s3:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - app-tier


networks:
  app-tier:
    driver: bridge