version: "3.9"
services:

  filestorage-service:
    build:
      context: .
      network: host
      dockerfile: filestorage-service/Dockerfile

  s3:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - app-tier

  filestorage-db:
    image: postgres:13.13-alpine3.19
    environment:
      - POSTGRES_DB=filestorage
      - POSTGRES_USER=filestorage
      - POSTGRES_PASSWORD=filestorage
    ports:
      - "55321:5432"

networks:
  app-tier:
    driver: bridge