spring:
  data:
  datasource:
    fs:
      driver-class-name: org.postgresql.Driver
      username: filestorage
      password: filestorage
      url: jdbc:postgresql://127.0.0.1:55321/filestorage
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,metrics,info,health"
  server:
    port: 8081

server:
  port: 8080

logging.level:
  com.flocktory: DEBUG
  org.springframework.boot.autoconfigure.flyway: DEBUG
  org.flywaydb: DEBUG
  org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
